from itertools import count
from math import sqrt, floor
from util import nth

def isprime(n):
    """Returns True/False depending on whether n is prime"""
    if n % 2 == 0: return False
    for i in xrange(3, int(sqrt(n))+1, 2):
        if n % i == 0: return False
    return True

def genprimes():
    """A generator that generates primes by simply iterating and checking"""
    for n in count(5, 2):
        if isprime(n): yield n

if __name__ == "__main__":
    prime_gen = genprimes()
    # 10,001st prime is 9998th prime generated by genpriems() because
    # isprime(n) doesn't count 2 and 3 as primes (for simplicity) and
    # genprimes() starts at 5 and skips even numbers
    print nth(prime_gen, 9998)
